// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    'inputBoard': string;
    'userinput': string;
}
declare var cssExports: CssExports;
export = cssExports;
