// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'message': string;
  'messageItem': string;
  'userDialogue': string;
  'username': string;
}
declare var cssExports: CssExports;
export = cssExports;
